Added JEST/ENZYME tests for components
HR-Mega-Bites/review-service pull request #10
Opened 2018-04-19 20:01 UTC by chobojai123

Please review my sample testing files for my components and I used Jest/Enzyme for them. All tests have passed via terminal when i run npm run test. You can ignore all other files other than the test files.

2018-04-19 20:03 UTC, chobojai123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PR David's basic jest/enzyme test files for react components](https://trello.com/c/IE9typHV/44-pr-davids-basic-jest-enzyme-test-files-for-react-components)

2018-04-19 23:30 UTC, careyl96 requested changes
Looks good other than a few things here and there. Fix those up and we'll be good to go

2018-04-19 23:30 UTC, CareyL96 commented on tests/about.test.js
> +  it('renders correctly', () => {
change to it('should render correctly')

2018-04-19 23:30 UTC, CareyL96 commented on tests/app.test.js
> +import App from '../client/src/App.jsx';
import components last

2018-04-19 23:30 UTC, CareyL96 commented on tests/comment.test.js
> +import Comment from '../client/src/Comment.jsx';
import components last

2018-04-19 23:30 UTC, CareyL96 commented on tests/comment.test.js
> +  it('correctly renders info section', () => {
include spaces after each block

2018-04-20 00:20 UTC, dcheng1290 commented
Updated import orders and spacing after blocks. Thanks.

2018-04-20 00:58 UTC, careyl96 submitted a review, later dismissed
looks good!

2018-04-20 01:36 UTC, careyl96 approved these changes

2018-04-20 01:38 UTC, merged